### ISSUE TITLE
卡在 [EB|#LOG:DT] [EB|#LOG:EXITBS:START]

### ISSUE THREAD

**Issue by onlysu** [QQ-War/EFI-X270#1]
Hi，采用你的EFI，由于没有提供Boot，所以我下载了原版opencore release补充了bootx64文件，但是进入苹果开机进度条，卡在了EB，按照网上教程关闭vt-d，也是不行

**Comment by QQ-War** [comment]
opencore的0.9.2的boot。不过用windows的boot然后编辑下添加opencore.efi也可以。
能进入，说明不是opencore文件的问题，那还是配置问题。
等等，我更新下吧，最近把USBMAP重做了，睡眠啥的效果更好了。

**Comment by onlysu** [comment]
好的，太感谢了，期待更新。
是的，我下载的0.9.2的boot，可以进入苹果进度条，系统用的Catalina10.15.7；
但是进度条一半之后，闪屏后继续前进，看起来是要进入系统的时候，就突然自动关机了，尝试多次依旧这个问题；
不确定是否是我接了HDMI的原因引起的（由于笔记本内屏损坏，只能接HDMI使用）

我的型号配置，看起来和你一样，不知道是否还需要替换自己的DSDT；
我原来是用过Clover，这次是第一次玩OC。

**Comment by QQ-War** [comment]
直接上传了7z文件，不想再操作git了。。。
DSDT不要动，OC里用SSDT。

**Comment by onlysu** [comment]
非常感谢，晚上我再试一下

**Comment by onlysu** [comment]
Hi，咨询个问题，我使用了你最新上传的EFI文件，但是依旧启动到了白苹果滚动条完毕后，闪屏一下就自动关机了；然后打开了-v ，然后没有看到特别的错误，跑码顺利结束了，到了白苹果还是关机了，不知道这个问题是否有遇到？
--------我重新恢复了bios，已经可以正常安装了，非常感谢！

**Comment by onlysu** [comment]
还是想问一下，我查询了X270的bios的CFG是锁死的，网上一直说要禁用，但是貌似X270也能正常使用？
